### ISSUE TITLE
not able to install distribution

### ISSUE THREAD

**Issue by ghost** [benliles/djangopypi#27]
I can see the python package that I created with distutil, but I can't install it from the server.  Looks like it is having problems with routing....
any ideas? 
Trying to access the project from the web interface:

Using the URLconf defined in chi.urls, Django tried these URL patterns, in this order:
^$ [name='djangopypi-root']
^packages/$ [name='djangopypi-package-index']
^simple/$ [name='djangopypi-package-index-simple']
^search/$ [name='djangopypi-search']
^pypi/$ [name='djangopypi-release-index']
^rss/$ [name='djangopypi-rss']
^simple/(?P<package>[\w\d_.-]+)/$ [name='djangopypi-package-simple']
^pypi/(?P<package>[\w\d_.-]+)/$ [name='djangopypi-package']
^pypi/(?P<package>[\w\d_.-]+)/rss/$ [name='djangopypi-package-rss']
^pypi/(?P<package>[\w\d_.-]+)/doap.rdf$ [name='djangopypi-package-doap']
^pypi/(?P<package>[\w\d_.-]+)/manage/$ [name='djangopypi-package-manage']
^pypi/(?P<package>[\w\d_.-]+)/manage/versions/$ [name='djangopypi-package-manage-versions']
^pypi/(?P<package>[\w\d_.-]+)/(?P<version>[\w\d_.-]+)/$ [name='djangopypi-release']
^pypi/(?P<package>[\w\d_.-]+)/(?P<version>[\w\d_.-]+)/doap.rdf$ [name='djangopypi-release-doap']
^pypi/(?P<package>[\w\d_.-]+)/(?P<version>[\w\d_.-]+)/manage/$ [name='djangopypi-release-manage']
^pypi/(?P<package>[\w\d_.-]+)/(?P<version>[\w\d_.-]+)/metadata/$ [name='djangopypi-release-manage-metadata']
^pypi/(?P<package>[\w\d_.-]+)/(?P<version>[\w\d_.-]+)/files/$ [name='djangopypi-release-manage-files']
^pypi/(?P<package>[\w\d_.-]+)/(?P<version>[\w\d_.-]+)/files/upload/$ [name='djangopypi-release-upload-file']
^admin/
The current URL, pypi/daemon/3.0/dists/daemon-3.0.zip, didn't match any of these.

**Comment by benliles** [comment]
The url for the release file, daemon-3.0.zip, will depend on your Django media directory settings. It's not likely going to be a url like the one provided. If you uploaded the release, you can view the release and see where Django stored it.
