### ISSUE TITLE
Default settings.py should include CSRF middleware

### ISSUE THREAD

**Issue by coderanger** [benliles/djangopypi#4]
Without CsrfViewMiddleware and CsrfResponseMiddleware, you can't get past the login form.

**Comment by coderanger** [comment]
On a related note, if these are enabled I get CSRF errors from the root() view when uploading from distutils. Kind of a catch-22.

**Comment by jimcook** [comment]
I uploaded [a patch](http://gist.github.com/551955) that fixes this problem for me.  Perhaps you can apply it to the code in the repository.

Note: I'm a django beginner.  I just followed the friendly advice in the error message that popped up after an attempted login.

**Comment by benliles** [comment]
I included your patch in my repository; however, I do not maintain the chishop project on http://pypi.python.org. You'll need to contact Ask about getting a new version of chishop published.
