### ISSUE TITLE
[question] write up on how it works

### ISSUE THREAD

**Issue by ericoporto** [benliles/djangopypi#58]
Hey, I know this is old unmaintained code, but I would like to understand the concepts and how the system works.

If you have a blog and have written about this code or if it haven't, I would like to ask to please write about this code. 

As is, though, I am already reading and trying to understand it's blocks. Thanks for opening your code here!

**Comment by benliles** [comment]
I did not write anything up about it at the time and it's probably not compatible any longer.

The overall idea was to provide private package hosting with the Python Package Index interface that proxied to pypi.python.org for any unknown packages. When publishing or installing a package, you can configure the package index address to use.

**Comment by ericoporto** [comment]
Thanks for explaining the purpose! :)
